### ISSUE TITLE
Incompatible with Switch Firmware 12.0.0+

### ISSUE THREAD

**Issue by omar117** [nullstalgia/UARTSwitchCon#1]
Estoy usando un  ESP-WROOM-32, no se conecta a la Nintendo Switch, no me arroga un tipo de error, solo me muestra el siguiente mensaje: authentication success: Nintendo Switch y la respectiva mac, me muestra varias veces el mensaje authentication success: Nintendo Switch sin poder conectarse a la NIntendo Switch, alguna idea de lo que este pasando.

**Comment by nullstalgia** [comment]
Disculpas por cualquier malentendido, estoy usando Google Translate.

Es posible que se esté conectando correctamente y esperando la entrada del
puerto serie.

¿Qué tipo de controlador estás emulando?

Confirme si tiene abierto el menú del controlador. "Buscar / emparejar
controladores". En el menú de inicio después de presionar el icono del
controlador.

La animación de la ranura del controlador con un indicador de botón es una
señal de que el ESP32 se está conectando.


No he probado este programa con el último firmware de Nintendo Switch.

**Comment by omar117** [comment]
No hay problema al contrario gracias por la ayuda, estoy emulando un joycon (L), si tengo el menú del controlador "buscar / emparejar controladores", sospecho que sea por el firmware  de Nintendo Switch, no se si me puedas confirmar si funciona en la ultimo firmware de la Nintendo Switch

**Comment by omar117** [comment]
GG, tal parece es el firmware 12 de la Nintendo Switch, tengo custom firmware en la versión 11.0.1 y funciona correctamente el esp32, no se si tenga solución pero por el momento dudo que funcione el esp32 en una versión actual de firmware de la Nintendo Switch.

**Comment by omar117** [comment]
Efectivamente acabo de confirmar que es el firmware 12 de la Nintendo Switch. Tal parece que se esta trabajando en ello https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/issues

**Comment by nullstalgia** [comment]
Ha pasado un tiempo desde que trabajé en este proyecto. Me suscribiré a esos hilos y los vigilaré. Tal vez pueda probar algunas de mis propias travesuras, si tengo tiempo. 😛 

Gracias por informarme sobre esto y por encontrar un problema relevante. ¡Mantenerse a salvo!

**Comment by nullstalgia** [comment]
Notes to self:

https://github.com/Brikwerk/nxbt/commits/v12_fix

Going to attempt a fix. Need to get my Linux configuration working again first, however. I'll update this post if I make any progress.

**Comment by jadenguy** [comment]
Check out the latest joycontrol. https://github.com/Poohl/joycontrol

**Comment by nullstalgia** [comment]
Thanks to the amazing work of @mizuyoukanao , this project is now compatible with Switch Firmware 12.0.0+.

I will put a new release with precompiled binaries very soon.

Hopefully you see this and my appreciation of your work. Many thanks.
