### ISSUE TITLE
Switch cannot find ESP32

### ISSUE THREAD

**Issue by jiangotto** [nullstalgia/UARTSwitchCon#6]
Switch cannot find ESP32, but I can find it using my phone.
Using ESP-WROOM-32 module ( ESP32-D0WD-V3 )

**Comment by nullstalgia** [comment]
Which binary are you using? And which controller type?

And are you using the most recent files?

**Comment by jiangotto** [comment]
PRO-UART0.bin
yes, the latest release

**Comment by nullstalgia** [comment]
I just tested that file with two different ESP32's on my latest firmware Switch, no issue.

How are you trying to connect the controller?

The way to connect is after the ESP32 is flashed and powered, going into the "Change Grip/Order" menu in the Controllers menu, and then it should connect.

Edit: I see your fork of my project! Awesome to see someone making use of my work! And just as I'm getting into Splatoon again too. 

Anyway, in the pictures of that I saw you're using a Switch Lite. Do you have access to a normal Switch or even an OLED? I only have a normal Switch, so I don't know if the Lite has some extra weirdness. In all reality, it *shouldn't*, the consoles are practically identical. But I guess it's possible that there's a difference in how it's announcing itself to the ESP?

**Comment by nullstalgia** [comment]
Okay, I think I understand your question a little more.

If someone is having trouble running the firmware, a good idea is to erase the ESP32's flash with the command `esptool.py erase_flash` and then re-flash the firmware.

Doing that will confirm that the user is able to talk to their ESP successfully, as well as generate a new random MAC Address for the ESP32 to use. The firmware generates a new MAC Address when it starts for the first time, and then saves it into flash so it doesn't look like a new "controller" each boot-up.

EDIT: One last suggestion I can give, is pull GPIO 15 to Ground (GND). That will tell the bootloader to be quiet during startup, and some development boards will reset the board when connecting via Serial.

**Comment by jiangotto** [comment]
Your projects are awesome! I rewrited a part of your QT project, and integrated esptool into it.
I tested on my own switch lite and it worked very well. Many people helped me to test it on switch and switch oled, and it worked. But about 3 or 4 people told me they had such a problem.

**Comment by jiangotto** [comment]
I will try to erase flash first, thanks for your suggestion!
